# Generated by Django 5.2.2 on 2025-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marn", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=100)),
                ("experience_years", models.IntegerField()),
                ("charge", models.CharField(max_length=50)),
                ("visa_type", models.CharField(max_length=100)),
                ("booking_preference", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("success_rate", models.CharField(max_length=20)),
                ("language", models.CharField(max_length=100)),
                ("employment_type", models.CharField(max_length=50)),
                ("google_rating", models.FloatField()),
                ("availability", models.CharField(max_length=100)),
                ("website", models.URLField()),
            ],
        ),
    ]
